import XCTest

@testable import BSONSerializationTests

var tests: [XCTestCaseEntry] = [
	testCase([
	]),
	testCase([
		("testDecodeEmptyBSONFromData", BSONSerializationTests.testDecodeEmptyBSONFromData),
		("testDecodeKeyAbcValDefFromData", BSONSerializationTests.testDecodeKeyAbcValDefFromData),
		("testSimpleEmbeddedDocFromData", BSONSerializationTests.testSimpleEmbeddedDocFromData),
		("testSimpleArrayFromData", BSONSerializationTests.testSimpleArrayFromData),
		("testInvalidFirstKeySimpleArrayFromData", BSONSerializationTests.testInvalidFirstKeySimpleArrayFromData),
		("testInvalidSecondKeySimpleArrayFromData", BSONSerializationTests.testInvalidSecondKeySimpleArrayFromData),
		("testPerformanceDecode4242EmptyDictionaryFromData", BSONSerializationTests.testPerformanceDecode4242EmptyDictionaryFromData),
		("testDecodeEmptyBSONFromStream", BSONSerializationTests.testDecodeEmptyBSONFromStream),
		("testSimpleEmbeddedDocFromStream", BSONSerializationTests.testSimpleEmbeddedDocFromStream),
		("testSizeEmptyBSON", BSONSerializationTests.testSizeEmptyBSON),
		("testSizeSimpleEmbeddedBSON", BSONSerializationTests.testSizeSimpleEmbeddedBSON),
		("testSizeEmbeddedArrayBSON", BSONSerializationTests.testSizeEmbeddedArrayBSON),
		("testSizeEmbeddedBSONsInArrayBSON", BSONSerializationTests.testSizeEmbeddedBSONsInArrayBSON),
		("testEncodeEmptyBSONToData", BSONSerializationTests.testEncodeEmptyBSONToData),
		("testEncodeSimpleBSONToData", BSONSerializationTests.testEncodeSimpleBSONToData),
		("testEncodeSimpleEmbeddedBSONToData", BSONSerializationTests.testEncodeSimpleEmbeddedBSONToData),
		("testEncodeEmptyBSONToStream", BSONSerializationTests.testEncodeEmptyBSONToStream),
		("testEncodeSimpleEmbeddedBSONToStream", BSONSerializationTests.testEncodeSimpleEmbeddedBSONToStream),
		("testEncodeDecodeEmptyBSONUsingData", BSONSerializationTests.testEncodeDecodeEmptyBSONUsingData),
		("testEncodeDecodeSimpleOneEmptyKeyBSONUsingData", BSONSerializationTests.testEncodeDecodeSimpleOneEmptyKeyBSONUsingData),
		("testEncodeDecodeSimpleOneEmptyValBSONUsingData", BSONSerializationTests.testEncodeDecodeSimpleOneEmptyValBSONUsingData),
		("testEncodeDecodeSimpleOneEmptyKeyAndValBSONUsingData", BSONSerializationTests.testEncodeDecodeSimpleOneEmptyKeyAndValBSONUsingData),
		("testEncodeDecodeSimpleOneKeyBSONUsingData", BSONSerializationTests.testEncodeDecodeSimpleOneKeyBSONUsingData),
		("testEncodeDecodeSimpleTwoKeysBSONUsingData", BSONSerializationTests.testEncodeDecodeSimpleTwoKeysBSONUsingData),
		("testEncodeDecodeSimpleNilValBSONUsingData", BSONSerializationTests.testEncodeDecodeSimpleNilValBSONUsingData),
		("testEncodeDecodeSimpleBoolValBSONUsingData", BSONSerializationTests.testEncodeDecodeSimpleBoolValBSONUsingData),
		("testEncodeDecodeSimpleIntValBSONUsingData", BSONSerializationTests.testEncodeDecodeSimpleIntValBSONUsingData),
		("testEncodeDecodeSimpleInt32ValBSONUsingData", BSONSerializationTests.testEncodeDecodeSimpleInt32ValBSONUsingData),
		("testEncodeDecodeSimpleInt64ValBSONUsingData", BSONSerializationTests.testEncodeDecodeSimpleInt64ValBSONUsingData),
		("testEncodeDecodeSimpleDouble64ValBSONUsingData", BSONSerializationTests.testEncodeDecodeSimpleDouble64ValBSONUsingData),
		("testEncodeDecodeSimpleDouble128ValBSONUsingData", BSONSerializationTests.testEncodeDecodeSimpleDouble128ValBSONUsingData),
		("testEncodeDecodeSimpleDateValBSONUsingData", BSONSerializationTests.testEncodeDecodeSimpleDateValBSONUsingData),
		("testEncodeDecodeSimpleRegexValBSONUsingData", BSONSerializationTests.testEncodeDecodeSimpleRegexValBSONUsingData),
		("testEncodeDecodeSimpleEmbeddedDocValBSONUsingData", BSONSerializationTests.testEncodeDecodeSimpleEmbeddedDocValBSONUsingData),
		("testEncodeDecodeSimpleArrayValBSONUsingData", BSONSerializationTests.testEncodeDecodeSimpleArrayValBSONUsingData),
		("testEncodeDecodeSimpleBSONTimeStampValBSONUsingData", BSONSerializationTests.testEncodeDecodeSimpleBSONTimeStampValBSONUsingData),
		("testEncodeDecodeSimpleBSONBinaryValBSONUsingData", BSONSerializationTests.testEncodeDecodeSimpleBSONBinaryValBSONUsingData),
		("testEncodeDecodeSimpleBSONObjectIdValBSONUsingData", BSONSerializationTests.testEncodeDecodeSimpleBSONObjectIdValBSONUsingData),
		("testEncodeDecodeSimpleJSValBSONUsingData", BSONSerializationTests.testEncodeDecodeSimpleJSValBSONUsingData),
		("testEncodeDecodeSimpleJSWithScopeValSimpleScopeBSONUsingData", BSONSerializationTests.testEncodeDecodeSimpleJSWithScopeValSimpleScopeBSONUsingData),
		("testEncodeDecodeSimpleMinKeyValBSONUsingData", BSONSerializationTests.testEncodeDecodeSimpleMinKeyValBSONUsingData),
		("testEncodeDecodeSimpleMaxKeyValBSONUsingData", BSONSerializationTests.testEncodeDecodeSimpleMaxKeyValBSONUsingData),
		("testEncodeDecodeSimpleMongoDBPointerKeyValBSONUsingData", BSONSerializationTests.testEncodeDecodeSimpleMongoDBPointerKeyValBSONUsingData),
		("testEncodeDecodeManyEmbeddedBSONUsingData", BSONSerializationTests.testEncodeDecodeManyEmbeddedBSONUsingData),
		("testEncodeDecodeEmptyBSONUsingStream", BSONSerializationTests.testEncodeDecodeEmptyBSONUsingStream),
		("testEncodeDecodeSimpleOneEmptyKeyBSONUsingStream", BSONSerializationTests.testEncodeDecodeSimpleOneEmptyKeyBSONUsingStream),
		("testEncodeDecodeSimpleOneEmptyValBSONUsingStream", BSONSerializationTests.testEncodeDecodeSimpleOneEmptyValBSONUsingStream),
		("testEncodeDecodeSimpleOneEmptyKeyAndValBSONUsingStream", BSONSerializationTests.testEncodeDecodeSimpleOneEmptyKeyAndValBSONUsingStream),
		("testEncodeDecodeSimpleOneKeyBSONUsingStream", BSONSerializationTests.testEncodeDecodeSimpleOneKeyBSONUsingStream),
		("testEncodeDecodeSimpleTwoKeysBSONUsingStream", BSONSerializationTests.testEncodeDecodeSimpleTwoKeysBSONUsingStream),
		("testEncodeDecodeSimpleNilValBSONUsingStream", BSONSerializationTests.testEncodeDecodeSimpleNilValBSONUsingStream),
		("testEncodeDecodeSimpleBoolValBSONUsingStream", BSONSerializationTests.testEncodeDecodeSimpleBoolValBSONUsingStream),
		("testEncodeDecodeSimpleIntValBSONUsingStream", BSONSerializationTests.testEncodeDecodeSimpleIntValBSONUsingStream),
		("testEncodeDecodeSimpleInt32ValBSONUsingStream", BSONSerializationTests.testEncodeDecodeSimpleInt32ValBSONUsingStream),
		("testEncodeDecodeSimpleInt64ValBSONUsingStream", BSONSerializationTests.testEncodeDecodeSimpleInt64ValBSONUsingStream),
		("testEncodeDecodeSimpleDouble64ValBSONUsingStream", BSONSerializationTests.testEncodeDecodeSimpleDouble64ValBSONUsingStream),
		("testEncodeDecodeSimpleDouble128ValBSONUsingStream", BSONSerializationTests.testEncodeDecodeSimpleDouble128ValBSONUsingStream),
		("testEncodeDecodeSimpleDateValBSONUsingStream", BSONSerializationTests.testEncodeDecodeSimpleDateValBSONUsingStream),
		("testEncodeDecodeSimpleRegexValBSONUsingStream", BSONSerializationTests.testEncodeDecodeSimpleRegexValBSONUsingStream),
		("testEncodeDecodeSimpleEmbeddedDocValBSONUsingStream", BSONSerializationTests.testEncodeDecodeSimpleEmbeddedDocValBSONUsingStream),
		("testEncodeDecodeSimpleArrayValBSONUsingStream", BSONSerializationTests.testEncodeDecodeSimpleArrayValBSONUsingStream),
		("testEncodeDecodeSimpleBSONTimeStampValBSONUsingStream", BSONSerializationTests.testEncodeDecodeSimpleBSONTimeStampValBSONUsingStream),
		("testEncodeDecodeSimpleBSONBinaryValBSONUsingStream", BSONSerializationTests.testEncodeDecodeSimpleBSONBinaryValBSONUsingStream),
		("testEncodeDecodeSimpleBSONObjectIdValBSONUsingStream", BSONSerializationTests.testEncodeDecodeSimpleBSONObjectIdValBSONUsingStream),
		("testEncodeDecodeSimpleJSValBSONUsingStream", BSONSerializationTests.testEncodeDecodeSimpleJSValBSONUsingStream),
		("testEncodeDecodeSimpleJSWithScopeValSimpleScopeBSONUsingStream", BSONSerializationTests.testEncodeDecodeSimpleJSWithScopeValSimpleScopeBSONUsingStream),
		("testEncodeDecodeSimpleMinKeyValBSONUsingStream", BSONSerializationTests.testEncodeDecodeSimpleMinKeyValBSONUsingStream),
		("testEncodeDecodeSimpleMaxKeyValBSONUsingStream", BSONSerializationTests.testEncodeDecodeSimpleMaxKeyValBSONUsingStream),
		("testEncodeDecodeSimpleMongoDBPointerKeyValBSONUsingStream", BSONSerializationTests.testEncodeDecodeSimpleMongoDBPointerKeyValBSONUsingStream),
		("testEncodeDecodeOneEmbeddedBSONUsingStream", BSONSerializationTests.testEncodeDecodeOneEmbeddedBSONUsingStream),
		("testEncodeDecodeTwoEmbeddedBSONUsingStream", BSONSerializationTests.testEncodeDecodeTwoEmbeddedBSONUsingStream),
		("testEncodeDecodeManyEmbeddedBSONUsingStream", BSONSerializationTests.testEncodeDecodeManyEmbeddedBSONUsingStream),
		("testIsValidBSONDoc1", BSONSerializationTests.testIsValidBSONDoc1),
		("testIsValidBSONDoc2", BSONSerializationTests.testIsValidBSONDoc2),
		("testIsValidBSONDoc3", BSONSerializationTests.testIsValidBSONDoc3),
		("testIsInvalidBSONDoc1", BSONSerializationTests.testIsInvalidBSONDoc1),
		("testIsInvalidBSONDoc2", BSONSerializationTests.testIsInvalidBSONDoc2),
	]),
	testCase([
		("testReadSmallerThanBufferData", BufferedInputStreamTests.testReadSmallerThanBufferData),
		("testReadBiggerThanBufferData", BufferedInputStreamTests.testReadBiggerThanBufferData),
	]),
	testCase([
	]),
]
XCTMain(tests)
